# Node.js current, active, and maintenance LTS versions
# https://nodejs.org/en/about/releases/
# current LTS: 24.x
# active LTS: 22.x
# maintenance LTS: 20.x
# Next LTS: 26.x
# Node.js 26 LTS will begin mid April 2026
# Update this file when a new LTS version is released
FROM node:24

# nx is v21 at the time of writing
# I'm going to tag this image with the version of nx
RUN npm add --global nx
# Angular is v20 at the time of writing
RUN npm install -g @angular/cli
